container:
  image: debian
  cpu: 8
  memory: 32G
  kvm: true
  timeout_in: 120m
task:
 script:
    - bash test.sh

docker_builder:
  name: Test
  timeout_in: 120m
  test_script:
    - bash test.sh

task:
  name: Linux
  compute_engine_instance:
    image_project: cirrus-images
     image: family/docker-kvm
     platform: linux
     cpu: 16
     memory: 32G
   setup_script:
     - bash test.sh
