version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - run:
          name: "Test"
          command: |
            ip address show
            ss -an
            df -h
            free -h
            lscpu
            systemd-detect-virt
            egrep -o '(vmx|svm)' /proc/cpuinfo && echo VT:yes || echo VT:no
            ps -ef
