name: GitHub CI Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: df
        run: df -h

      - name: free
        run: free -h

      - name: cpuinfo
        run: lscpu

      - name: systemd-detect-virt
        run: systemd-detect-virt

      - name: ss
        run: ss -antl
